version: '3'

services:
  db:
    container_name: workoop-bd
    networks:
      - core
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "25432:5432"
    volumes:
      - /docker/postgres-data:/var/lib/postgresql/data
  backend:
    container_name: workoop-backend
    networks:
      - core
    build: ./backend
    image: workoop:latest
    command: bash -c "python manage.py makemigrations &&
                      python manage.py migrate &&
                      python manage.py runserver 0.0.0.0:8000 &&
                      echo \"from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'admin@example.com', 'pass')\" | python manage.py shell"
    volumes: 
      - ./backend:/backend
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8000:8000
    depends_on:
      - db
  frontend:
    container_name: workoop-frontend
    networks:
      - core
    build:
      context: frontend
      dockerfile: Dockerfile
    command:
      'yarn run dev'
    ports:
      - 3000:3000
networks:
  core:
    external: true