import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
// https://stackoverflow.com/questions/71885441/next-js-getserversideprops-is-not-working-using-docker

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>Next app</main>
      <h1>Next</h1>
      <p>Que facha que es next</p>
    </div>
  );
};

export default Home;
